export const Countries = [
  { name: "Uzbekistan", flag: "UZ" },
  { name: "Kazakhstan", flag: "KZ" },
  { name: "Kyrgyzstan", flag: "KG" },
  { name: "Tajikistan", flag: "TJ" },
  { name: "Turkmenistan", flag: "TM" },
  { name: "Russia", flag: "RU" },
  { name: "China", flag: "CN" },
  { name: "India", flag: "IN" },
  { name: "Pakistan", flag: "PK" },
  { name: "Turkey", flag: "TR" },
  { name: "United States", flag: "US" },
  { name: "Canada", flag: "CA" },
  { name: "Brazil", flag: "BR" },
  { name: "Argentina", flag: "AR" },
  { name: "Mexico", flag: "MX" },
  { name: "Germany", flag: "DE" },
  { name: "France", flag: "FR" },
  { name: "Italy", flag: "IT" },
  { name: "Spain", flag: "ES" },
  { name: "United Kingdom", flag: "GB" },
  { name: "Australia", flag: "AU" },
  { name: "Japan", flag: "JP" },
  { name: "South Korea", flag: "KR" },
  { name: "Indonesia", flag: "ID" },
  { name: "Saudi Arabia", flag: "SA" },
  { name: "United Arab Emirates", flag: "AE" },
  { name: "Egypt", flag: "EG" },
  { name: "South Africa", flag: "ZA" },
  { name: "Switzerland", flag: "CH" },
  { name: "Norway", flag: "NO" }
]

export const days_array = [10,15,30,45,60,90,180,365]