export const Heading = [
  {
    title: "Insurance for visa to Russia",
    lang: 'GB',
  },
  {
    title: "Страхование на визу в Россию",
    lang: 'RU',
  },
  {
    title: "Rossiyaga viza uchun sug'urta",
    lang: 'UZ',
  },
];

export const FormTranslate = [
  {
    lang:"GB",
    first:"The first trip date:",
    last:"The last trip date:",
    days_amount:"Amount of days: ",
    chechbox: "Annual insurance policy",
    number_days: "Number of days in a year: ",
    days:"days",
    submit:"Submit",
    travelers: "Travelers",
    age: "age",
    tourist_number: "Number of tourists",
    years: "years",
    add_tourist:"Add tourist",
    tourist:"tourist",
    calc:"Calculate",
    Your_contract:"Your contract",
    insurance_policy: "What is included in Your insurance policy:",
    partnership:"In partnership with:",
    insurance_coverage:"Insurance coverage:",
    services:['Covid-19',"Doctor's home visit","Hospitalization","Visit to the clinic","Medication costs","Transportation"],
    cost_policy:"Cost of the insurance policy:",
    show_all:"Show all",
  },
  {
  lang: "RU",
  first: "Дата первой поездки:",
  last: "Дата последней поездки:",
  days_amount: "Количество дней: ",
  chechbox: "Годовой страховой полис",
  number_days: "Количество дней в году: ",
  days: "дней",
  submit: "Отправить",
  travelers: "Путешественники",
  age: "лет",
  tourist_number: "Количество туристов",
  years: "лет",
  add_tourist:"Добавить туристa",
  tourist: "турист",
  calc:"Рассчитать",
  Your_contract:"Ваш страховой договор",
  insurance_policy: "Что входит в Ваш страховой полис:",
  partnership:"В партнерстве с:",
  insurance_coverage:"Страховое покрытие:",
  services:["Covid-19","Вызов врача на дом","Госпитализация","Посещение клиники","Затраты на медикаменты","Транспортировка"],
  cost_policy:"Стоимость страхового полиса:",
  show_all:"Показать все",
},
{
  lang: "UZ",
  first: "Birinchi safar sanasi:",
  last: "Oxirgi safar sanasi:",
  days_amount: "Kunlar soni: ",
  chechbox: "Yillik sug'urta polisi",
  number_days: "Bir yildagi kunlar soni: ",
  days: "kun",
  submit: "Yuborish",
  travelers: "Sayohatchilar",
  age: "yoshi",
  tourist_number: "Turistlar soni",
  years: "yosh",
  add_tourist:"Turist qo'shish",
  tourist: "turist",
  calc:"Hisoblash",
  Your_contract:"Sizning kontrakt",
  insurance_policy: "Sizning sug'urta polisi haqida qo'liq:",
  partnership:"Birlashma bilan:",
  insurance_coverage:"Sug'urta ko'rsatish:",
  services:["Covid-19","Shifokorning uyga tashrifi","Kasalxonaga yotqizish","Klinikaga tashrif buyurish","Dori-darmon xarajatlari","Transport"],
  cost_policy:"Sug'urta polisi narxi:",
  show_all:"Hammasini ko'rsatish",
}
]